name: "Setup dapptools environment"
description: "Setup a dapptools environment by adding problem matchers and optionally downloading and adding it to the PATH"
author: "Risedle"
inputs:
outputs:
runs:
  using: "docker"
  image: "Dockerfile"
