name: "Setup dapptools environment"
description: "Setup a dapptools environment by downloading and adding it to the PATH"
author: "Risedle"
inputs:
  tarball:
    description: "The tarball url of dapptools"
    required: false
    default: "https://github.com/dapphub/dapptools/archive/refs/tags/hevm/0.49.0.tar.gz"
  solc:
    description: "The version of solidity compiler"
    required: false
    default: "solc_0_8_6"
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: dapp
    - run: nix-env -iA dapp hevm seth ethsign "solc-static-versions.${{ inputs.solc }}" -f ${{ inputs.tarball }}
      shell: bash
branding:
  icon: "star"
  color: "black"