name: "Setup dapptools environment"
description: "Setup a dapptools environment by downloading and adding it to the PATH"
author: "Risedle"
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: dapp
    - run: nix-env -iA dapp hevm seth ethsign solc -f https://github.com/dapphub/dapptools/archive/refs/tags/hevm/0.49.0.tar.gz
      shell: bash
