name: setup-dapptools
on: [push]
jobs:
  default:
    runs-on: ubuntu-latest
    name: default
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - run: dapp --version
  custom-tarball:
    runs-on: ubuntu-latest
    name: custom tarball
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          tarball: "https://github.com/dapphub/dapptools/archive/master.tar.gz"
      - run: dapp --version
  custom-solc:
    runs-on: ubuntu-latest
    name: custom solc
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          solc: "solc-linux-amd64-v0.8.11+commit.d7f03943"
      - run: dapp --version
